//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AionQuests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AionQuests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AION Quests.
        /// </summary>
        internal static string aionQuests {
            get {
                return ResourceManager.GetString("aionQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asmodian.
        /// </summary>
        internal static string asmodian {
            get {
                return ResourceManager.GetString("asmodian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asmodians Quests.
        /// </summary>
        internal static string asmodiansQuests {
            get {
                return ResourceManager.GetString("asmodiansQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Abandon?.
        /// </summary>
        internal static string canAbandon {
            get {
                return ResourceManager.GetString("canAbandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Share?.
        /// </summary>
        internal static string canShare {
            get {
                return ResourceManager.GetString("canShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        internal static string classes {
            get {
                return ResourceManager.GetString("classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Level.
        /// </summary>
        internal static string clientLevel {
            get {
                return ResourceManager.GetString("clientLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect.
        /// </summary>
        internal static string collect {
            get {
                return ResourceManager.GetString("collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Items.
        /// </summary>
        internal static string collectItems {
            get {
                return ResourceManager.GetString("collectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data folder is missing!.
        /// </summary>
        internal static string dataMissing {
            get {
                return ResourceManager.GetString("dataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap dialogBackground {
            get {
                object obj = ResourceManager.GetObject("dialogBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elyo.
        /// </summary>
        internal static string elyo {
            get {
                return ResourceManager.GetString("elyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elyos Quests.
        /// </summary>
        internal static string elyosQuests {
            get {
                return ResourceManager.GetString("elyosQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extends Inventory?.
        /// </summary>
        internal static string extendsInventory {
            get {
                return ResourceManager.GetString("extendsInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extends Stigma?.
        /// </summary>
        internal static string extendsStigma {
            get {
                return ResourceManager.GetString("extendsStigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id.
        /// </summary>
        internal static string itemId {
            get {
                return ResourceManager.GetString("itemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Item Data.
        /// </summary>
        internal static string loadingItemData {
            get {
                return ResourceManager.GetString("loadingItemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading NPCs.
        /// </summary>
        internal static string loadingNpc {
            get {
                return ResourceManager.GetString("loadingNpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Quest Data.
        /// </summary>
        internal static string loadingQuestData {
            get {
                return ResourceManager.GetString("loadingQuestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Strings.
        /// </summary>
        internal static string loadingStrings {
            get {
                return ResourceManager.GetString("loadingStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string misc {
            get {
                return ResourceManager.GetString("misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        internal static string mission {
            get {
                return ResourceManager.GetString("mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pages.
        /// </summary>
        internal static string pages {
            get {
                return ResourceManager.GetString("pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing.
        /// </summary>
        internal static string parsing {
            get {
                return ResourceManager.GetString("parsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest.
        /// </summary>
        internal static string quest {
            get {
                return ResourceManager.GetString("quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Id.
        /// </summary>
        internal static string questId {
            get {
                return ResourceManager.GetString("questId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        internal static string quests {
            get {
                return ResourceManager.GetString("quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        internal static string races {
            get {
                return ResourceManager.GetString("races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Count.
        /// </summary>
        internal static string repeatCount {
            get {
                return ResourceManager.GetString("repeatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string step {
            get {
                return ResourceManager.GetString("step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        internal static string steps {
            get {
                return ResourceManager.GetString("steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops!!!.
        /// </summary>
        internal static string whoops {
            get {
                return ResourceManager.GetString("whoops", resourceCulture);
            }
        }
    }
}
